language: python
python:
- '3.6'
- '3.7'
install:
- "./.travis/install.sh"
- pipenv install -d codecov
script:
- "./.travis/run-test.sh"
after_success:
- codecov
env:
  global:
    secure: hOy7VAQqhzIXW2XqYBFYWCMGGMbqsrPbk+Fk3T41Rj5iTncvojSrlliY4Mum1GFEOK2H6/jkLDCrwwXhpF44a7BG/7o9cjsiA9XC224vse7F9SEU0ogznXrrvj2Kbdg4TXPEXmaWLHJ4yEGTx1pfVQ2HA7DDxTe/kJ5iF806M60d/ASCeiiKa6YvIymwU//bDOBDQcN4taYWpgS7e/an2MwWx64tw325/nhsNTP7zyQq3fh3S+T+ZEhwoJM9K6FQFqMu/M1wOoKBY3rhecr10IgBxy5CN954fEJPjEkSFC3XfP43xauvXjeKMI99rCn3JijAWyCbhC4uWG8FhhqkLj8f1Z0MfU+Upl4GlIRObL695FBzAPqB5E/UNUYrgcSOyGOsgDYWkAc9qnWO3IPkXmDTlwJTaLn+038ZbaIlEb27nz5GjvLFDT6eHF8N4BzibEUc3XsurXI77r122UK7QuLkwlch4Na4wGqiRfhG58NzC2R7hI7adUTaDCuqIdwBIUGabR8WcAY7uIANTjn39OO7+jBSzN8wkFrqBKr4WHqJdPILWrUyqOz9Ty+vFVADQ8Xg+xI3sfrSTXa7UjnxtXVUBukJUxu66C7OxymIPA6rL1DvbjBTz6zEGgWk+w/iiTIlzRL2gmm4RThvei5RZD8FVGo5lLamam1koL6ZD1k=
