language: python
stages:
- unit-test
- build-test
- package-test
jobs:
  include:
  - stage: unit-test
    name: Unit Test
    script:
    - "./.travis/unit-test.sh"
    python: '3.6'
  - stage: unit-test
    name: Unit Test
    script:
    - "./.travis/unit-test.sh"
    python: '3.7'
  - stage: build-test
    name: Build Test
    script:
    - "./.travis/build-test.sh"
    python: '3.6'
  - stage: build-test
    name: Build Test
    script:
    - "./.travis/build-test.sh"
    python: '3.7'
  - stage: package-test
    name: Package Test
    script:
    - "./.travis/package-test.sh"
    python: '3.6'
  - stage: package-test
    name: Package Test
    script:
    - "./.travis/package-test.sh"
    python: '3.7'
install:
- "./.travis/install.sh"
- pipenv install -d codecov
after_success:
- codecov
env:
  global:
    secure: JF2PbJrx65c6XpKV2571hN4owJcSNrqoLw7s08Dvnqu/KcUoUW9o8uCL1bCqXuQVQ48+e2BGAeEbka59+JB+s2PG5x2G2sAXBZn+QL+0YwAbyT5GwIjFlOPlOsbor7ta8yrTXbHqqAOtDRKuc6eug4yHQtu0yCudUYYP3ufKX7aAS9D8Hl/0mJJyTwqyfSG8boEoP2zrcekCZGPTVCa2QJX2NKOkSZcVQruISQzOgJl0L1MxWTWe1xfMJyb/FhEoaSh1TIXvuYIpj1TTFc76P2PWZsHqmUn28+zj0MAzjuaDNO1ET/ZrImrrSMqTJLHSvpOvuvd8Xwj2Qhi6daFbZnj4JLczqSFbcPP9Y6QttlS+oRygUbrrzAQB/1kiEOZfCwPsnSuoXz7s4QLQiX4BBT84l4taEufBXW3tN9fpTjKLAA8SOCE0q7ZAU7Q11UGYteaMV0R0cxK1J2WqN5nwQ3LmRIIKUn/WE2gxVddSVvvrxhtlierOn48NxDc1gbS6g1204H7WLlj/1d9uqy669yRIomEJAO3YNAoXrh6Ulk7UmCf5amsh88na6LC+WQ6siXzyab7OS23FAe4F+K8mV80Q9H+eA219yqY65asXvg2yj2DoG3qM2tK7DVacWmEMwSXPnpbS/QyscxTcDCROZdqnW+VYfTkP8675uSYlB/4=
deploy:
  provider: releases
  api_key:
    secure: Rc5KzZD4ULDSZOi25NW+I1N973+9MX4yeQXfA/18tRsSFD6QmjjR8kvGv0ftd/mZCspzDEZeawzj8AopVKWjeAoj/nTMJ5avn0uGVAZLuQKeSquFJJfLXPySZd3RU53n8/9rlmX9cbgMo/6Kgm/Qwf8c7HCUciquJHvGa7lJwm7irNdJTS3mMsg4QqND73e7nUyTPNjm15BKx4kJ4cRdIdERjV7SgIw8j/8+oCY67I/Azpu5r4JAchVEvgCBlDDVkJXbyKnkoz7oej4fI4ypi33pSZXpnvEfIdUyZ6qUSsPBMQkO+WyGwFgGqTor3+kNKjgvh/ML7wAQBWhL1pMlyd4sfFVpjiIwsOcvRMbpSjb8ZKSpxGbuxwb/LEl6ToCD8XWSRw8cgq1gu3cBdE4qT9q8PVE/9wvFbGgIQoQFcK8ulIrD/bDDJQDQ8tYUeuVinKkHQ9FTdlC/OvWj+e+HDzQKbXULWL3cqVmfsdsolQ/rMQynG6Bcy7mxClz8Xq259VtLM58l4Y8rm9qRAVMvEe6L5z8NAPcQcidP8kt1zReZN6h7SeP/gN7MDIdGWpQV+MfTcyyE0sFr7AFffQzVUkrDQYxGbcDCDsiIEOHg/5yUnoa6g3aa6OKWhKVtpFWLLIskgLjgJjvXET+HLiHegJzF02gZfKyMbrjPWHdaFeQ=
  file: dist/*
  on:
    tags: true
  draft: true
